### ISSUE TITLE
Error when building Google Cloud ASR pipeline

### ISSUE THREAD

**Issue by DeBusscherePieter** [spokestack/spokestack-android#137]
Hi 👋

I'm trying to set up the Google Cloud ASR with this configuration:

```
var json: String? = null
        try {
            val  inputStream: InputStream = assets.open("service_account.json")
            json = inputStream.bufferedReader().use{it.readText()}
        } catch (ex: Exception) {
            ex.printStackTrace()
        }

        val builder = Spokestack.Builder()
            .withoutWakeword()
            .withoutNlu()
            .setProperty("spokestack-id", "my id")
            .setProperty("spokestack-secret", "my secret")
            .withAndroidContext(this)
            .addListener(listener)
        builder
            .pipelineBuilder
            .setProperty("google-credentials", json)
            .setProperty("language", "en-US")
            .useProfile("io.spokestack.spokestack.profile.VADTriggerGoogleASR")
        return builder.build()
```

Unfortunately, this configuration throws the following exception(s):

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mypackagename, PID: 26259
    java.lang.RuntimeException: Unable to start activity ComponentInfo{mypackagename.MainActivity}: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at io.spokestack.spokestack.SpeechPipeline.createComponents(SpeechPipeline.java:203)
        at io.spokestack.spokestack.SpeechPipeline.start(SpeechPipeline.java:182)
        at io.spokestack.spokestack.Spokestack.start(Spokestack.java:182)
        at mypackagename.MainActivity.onCreate(MainActivity.kt:54)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7814) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/auth/oauth2/ServiceAccountCredentials;
        at io.spokestack.spokestack.google.GoogleSpeechRecognizer.<init>(GoogleSpeechRecognizer.java:66)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at io.spokestack.spokestack.SpeechPipeline.createComponents(SpeechPipeline.java:203) 
        at io.spokestack.spokestack.SpeechPipeline.start(SpeechPipeline.java:182) 
        at io.spokestack.spokestack.Spokestack.start(Spokestack.java:182) 
        at mypackagename.MainActivity.onCreate(MainActivity.kt:54) 
        at android.app.Activity.performCreate(Activity.java:7955) 
        at android.app.Activity.performCreate(Activity.java:7944) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7814) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.auth.oauth2.ServiceAccountCredentials" on path: DexPathList[[zip file "/data/app/mypackagename-IVppXU7KnFHxIENF0_Db1w==/base.apk"],nativeLibraryDirectories=[/data/app/mypackagename-IVppXU7KnFHxIENF0_Db1w==/lib/arm64, /data/app/mypackagename-IVppXU7KnFHxIENF0_Db1w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.spokestack.spokestack.google.GoogleSpeechRecognizer.<init>(GoogleSpeechRecognizer.java:66) 
        at java.lang.reflect.Constructor.newInstance0(Native Method)
```

I'm using the .json file from the service account configured in GCP.
What could be the issue here? 

Thank you! 🙏

**Comment by space-pope** [comment]
Hi, and thanks for reaching out!

Thanks for posting the whole stacktrace—what it's telling you is not that there's a problem with your credentials, but that it's unable to find the class the Google Cloud Speech API uses to verify them.

Since Spokestack offers a variety of ASR providers, and on-device ASR is the default, these transitive dependencies aren't bundled by default (to keep the library as lightweight as possible). You'll need to include them explicitly in your app's `build.gradle`. This isn't covered in the readme since we're focused on the easiest/most frictionless use case there, but you can find more configuration info [on our website](https://www.spokestack.io/docs/android/getting-started#installation).

For your case, you'll want to include the following lines:
```
  implementation 'com.google.cloud:google-cloud-speech:1.25.1'
  implementation 'io.grpc:grpc-okhttp:1.36.0'
```

I've listed the most recent versions of those libraries as of this writing; the library itself was build against older versions, so if you get a different error on startup, let me know or try the versions listed in the documentation I linked above.

**Comment by DeBusscherePieter** [comment]
Hi @space-pope , thank you so much for the quick reply! That solved my problem 🙏 . Do you perhaps know what languages the Spokestack Cloud ASR supports?

**Comment by space-pope** [comment]
Great; glad to help!

Spokestack's cloud ASR is currently English-only, but we're always interested in feedback to help guide future expansions. What language(s) would you like to see supported in the future?

**Comment by space-pope** [comment]
I should note that the default ASR provider, Android's on-device ASR, is multilingual. The current version of the library doesn't expose a way to tell Android to _restrict_ its results to a given language, but that could be added if needed.

**Comment by DeBusscherePieter** [comment]
@space-pope Thanks for your reply. Dutch support would be wonderful!
